api/.gitignore
api/build/app.js
api/build/db.js
api/index.js
api/node_modules/.package-lock.json
api/package-lock.json
api/package.json
api/tsconfig.json

Acabo de configurar un poco nuestro package.json y las dependencias, añadí un paquete que ayuda con el tipado en Ts, creé e hice una pequeña configuración del servidor con express y configuré typescript para que compilará nuestros archivos .ts en la carpeta build, además dejé unos comentarios en app.tsx sobre cómo hacer correr el servidor unicamente o hacer que corra conectado con la DB desde index.js; el servidor ya corre haciendo "npm start"

Servidor Creado y Funcionando / Ts Configurado

---

client/devs-learning/package-lock.json
client/devs-learning/package.json

Se  instalo:
- React Redux
- Redux
- Readux Thunk
- Material UI

Instalacion de Librerias

---

client/devs-learning/package-lock.json
client/devs-learning/package.json
client/devs-learning/src/actions/actions.js
client/devs-learning/src/reducers/theReducer.js
client/devs-learning/src/store/store.js

Instalé las dependencias de Redux siguiendo lo que usamos en el PI.
Diganme si les parece que hay algo mal o está bien.
También cree la Store, y los archivos y modelos de Reducer y Actions. Los hice en JS porque todavía tengo que repasar TS.

Install Redux and React-redux

---

client/devs-learning/.gitignore
client/devs-learning/package-lock.json
client/devs-learning/package.json
client/devs-learning/src/components/searchbar/searchbar.tsx
client/devs-learning/src/router/index.tsx
client/devs-learning/src/views/Home.tsx
client/package-lock.json

Se creo la searchbar basica sin logica

Search bar

---

api/.env
api/.gitignore
api/db/db.js
api/db/models/Category.js
api/db/models/Course.js
api/node_modules/.package-lock.json
api/package-lock.json
api/package.json
client/devs-learning/package-lock.json
client/devs-learning/package.json
client/devs-learning/src/actions/actions.js
client/devs-learning/src/reducers/theReducer.js
client/devs-learning/src/store/store.js

En folder api creación de folder db el cual contiene:
- file db.js
- folder models inicialmente con 2 modelos: Course y Category

creacion de base de datos

---

client/devs-learning/src/components/Detail/CourseDetail.tsx
client/devs-learning/src/router/index.tsx

Les comparto lo que pude armar hasta ahora del componente detalle de curso. Está desconectado del redux, me faltan agregar las actions correspondientes para que el curso que se renderiza sea el que corresponda al estado global. Sin embargo, el modelo o interfase que usé para el componente, está basado en el modelo que armó Jona Villalba en la DB.
Repito que no está terminado pero para sumar funcionalidad a la página creo que se puede mergear a development.

Agrego componente detalle sin conexión a redux aún

---

client/devs-learning/src/components/Footer/Footer.tsx
client/devs-learning/src/router/index.tsx

Agrego el componente footer. Lo agregué a las rutas tambien.

Footer primer modelo

---

client/devs-learning/src/components/Cards/Card.tsx
client/devs-learning/src/components/Detail/CourseDetail.tsx
client/devs-learning/src/redux/courses/slice.ts

Falta renderizar las categories porque aún me tira error, pero el resto funciona.

Actualizo datos en Cards y /courseDetail 

---

client/devs-learning/src/components/Filter/Filter.tsx
client/devs-learning/src/components/searchbar/searchbar.tsx
client/devs-learning/src/redux/courses/actions.ts

se saco el filtro de categorias cuando se entra en una categoria especifica y se hizo responsive el filtro con searchbar

Filter categories2

---

client/devs-learning/src/components/Landing/LandingPage.tsx
client/devs-learning/src/components/navBar/NavBar.tsx
client/devs-learning/src/router/index.tsx

se agrego el landing en la ruta inicial y se movio home a courses

Rutas de landing y cursos

---

client/devs-learning/package-lock.json
client/devs-learning/package.json
client/devs-learning/src/components/Dashboards/DashboardAdmin.tsx
client/devs-learning/src/components/Dashboards/NavBarAdmin.tsx
client/devs-learning/src/router/index.tsx

Creo carpeta, componente y ruta borrador del dashboard de admin para continuar trabajando @Jonatan-R-Villalva

Borrador de Dashboard Admin

---

client/devs-learning/src/components/Filter/Filter.tsx
client/devs-learning/src/redux/courses/actions.ts
client/devs-learning/src/redux/courses/slice.ts
client/devs-learning/src/router/index.tsx
client/devs-learning/src/views/CoursePerCategories.tsx
client/devs-learning/src/views/Home.tsx

se arreglaron bugs del filtro y se agregaron mensajes de busqueda

Filtro arreglado

---

client/devs-learning/src/router/LoggedRoutes.tsx

No se si corresponde este PR o el de Dashboards que hizo Jona Villalba. Pero ese tiene conflictos.

Arreglo ruta admin

---

api/build/app.js
api/node_modules/.package-lock.json
api/package-lock.json
api/package.json
api/src/app.ts
api/src/routes/meli.ts
api/src/routes/mercadopago/meliProducts.ts
api/src/routes/mercadopago/mercadopago.ts
client/devs-learning/.env
client/devs-learning/src/views/Categories.tsx

se hizo las rutas del back de mercadopago

mercadopago back api

---

api/src/routes/mercadopago/meliProducts.ts
client/devs-learning/src/components/Cart/Cart.tsx
client/devs-learning/src/components/meliButton/meliButton.tsx

boton de pago que funciona, pero crea mas de un boton si se modifica el carrito

boton mercadopago 1

---

client/devs-learning/src/components/Cart/Cart.tsx
client/devs-learning/src/components/meliButton/meliButton.tsx
client/devs-learning/src/router/index.tsx

se corrigio el bug que multiplicaba los botones y se agrego un llamado en el index para que exista el boton la primera vez

boton corregido

---

client/devs-learning/src/router/LoggedRoutes.tsx

Modifico link, ahora estando logueado, cuando presiono en ir al perfil en el menú de la NavBar. Ahora redirije al perfil del usuario.

Profile button redirect to profile component

---

client/devs-learning/src/components/Dashboards/User/UserComment.tsx
client/devs-learning/src/components/Dashboards/User/UserCourses.tsx
client/devs-learning/src/components/Dashboards/User/UserRating.tsx
client/devs-learning/src/components/Dashboards/UserDashboard.tsx

Agrego borrador de Rating and Comments al perfil del usuario. Para agregar la funcionalidad faltan los get de la DB para obtener cursos comprados por usuario, y actualizar el modelo de Cursos para que incluya rating y comments..

Borrador Comments and Rating components en UserProfile

---

client/devs-learning/src/components/Cards/Card.tsx
client/devs-learning/src/components/Cart/CartCard.tsx
client/devs-learning/src/components/Courses/EditForm.tsx
client/devs-learning/src/components/Detail/CourseDetail.tsx
client/devs-learning/src/redux/courses/actions.ts
client/devs-learning/src/redux/courses/slice.ts

Agregamos propiedad Rating a Interface CoursoBack y actualizamos redux

---

client/devs-learning/src/components/Dashboards/User/UserComment.tsx
client/devs-learning/src/components/Dashboards/User/UserCourses.tsx
client/devs-learning/src/redux/users/actions.ts

Logré hacer que se renderice la tabla de cursos comprados por un usuario en el perfil de usuario. Queda todavia pendiente la funcionalidad de postear un comentario.

UserDash / Obtener cursos comprados

---

client/devs-learning/package-lock.json
client/devs-learning/package.json
client/devs-learning/src/components/Dashboards/Admin/UsersPanel.tsx
client/devs-learning/src/interfaces/CreateUserInterface.ts
client/devs-learning/src/redux/AllUsers/actions.ts
client/devs-learning/src/redux/AllUsers/slice.ts

Add Delete Users

---

client/devs-learning/src/components/Dashboards/Admin/UsersPanel.tsx
client/devs-learning/src/redux/AllUsers/actions.ts
client/devs-learning/src/redux/AllUsers/slice.ts

Update Ban Users

---

client/devs-learning/src/components/Dashboards/Admin/CoursesPanel.tsx

se crea el boton de editar curso pero al terminar me obliga a desloguearme para poder ver el cambio,

Courses admin3
